# Generated by Django 4.0.6 on 2022-10-09 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafter_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
