# Generated by Django 4.0.6 on 2022-07-16 01:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafter_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='category',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None),
        ),
    ]
