# Generated by Django 4.0.6 on 2022-07-06 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crafter_tracker', '0002_remove_project_images_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='resources',
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.URLField(max_length=400)),
                ('media_type', models.CharField(max_length=100)),
                ('notes', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='crafter_tracker.project')),
            ],
        ),
    ]
