# Generated by Django 4.0.6 on 2022-10-09 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafter_tracker', '0002_project_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
