# Generated by Django 4.0.6 on 2022-10-09 04:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crafter_tracker', '0003_project_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='complete_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 10, 9, 4, 16, 12, 50759, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
