# Generated by Django 4.0.6 on 2022-07-09 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crafter_tracker', '0003_remove_project_resources_resource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='materials',
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='resource',
            name='media_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('categories', models.CharField(max_length=255)),
                ('material_purchase_link', models.URLField(max_length=400)),
                ('notes', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='crafter_tracker.project')),
            ],
        ),
    ]
