# Generated by Django 4.0.6 on 2022-07-09 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crafter_tracker', '0004_remove_project_materials_alter_project_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='categories',
            new_name='category',
        ),
    ]
