# Generated by Django 4.1.2 on 2022-10-25 02:43

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('crafter_tracker', '0007_alter_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz0123456789', editable=False, length=20, max_length=20, prefix='', primary_key=True, serialize=False, unique=True),
        ),
    ]
