# Generated by Django 4.1.2 on 2022-10-25 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafter_tracker', '0008_alter_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
